name: y_music_player
description: A customizable Flutter music player.
publish_to: none
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  dio: ^5.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  just_audio: ^0.9.42
  on_audio_query: ^2.9.0
  permission_handler: ^11.3.1
  cached_network_image: ^3.4.1
  http: ^1.2.2
  logger: ^2.4.0
flutter:
  uses-material-design: true
